Repository networknt/light-4j, pull requests merged in 2019-07, with the labels that each got.

#564 Fixes merge to 1.6.x
  client/src/integration/resources/config/primary.crt
  client/src/integration/resources/config/primary.jks
  client/src/integration/resources/config/secondary.crt
  client/src/integration/resources/config/secondary.jks
  client/src/integration/resources/config/server.keystore
  client/src/integration/resources/config/server.truststore
  client/src/main/java/com/networknt/client/Http2Client.java
  client/src/test/resources/config/client.keystore
  client/src/test/resources/config/client.truststore
  config/src/main/java/com/networknt/config/Config.java
  pom.xml
  server/pom.xml
  server/src/integration/java/com/networknt/server/ConsulRegistryIT.java
  server/src/integration/resources/config/consul.yml
  server/src/integration/resources/config/handler.yml
  server/src/integration/resources/config/server.yml
  server/src/integration/resources/config/service.yml
  server/src/integration/resources/logback-test.xml
  server/src/main/java/com/networknt/server/Server.java
  server/src/test/resources/config/client.keystore
  server/src/test/resources/config/client.truststore
  server/src/test/resources/config/server.keystore
  server/src/test/resources/config/server.truststore
  utility/src/main/java/com/networknt/utility/TlsUtil.java
  utility/src/test/java/com/networknt/utility/TlsUtilTest.java
  utility/src/test/resources/config/client.keystore
  utility/src/test/resources/config/client.truststore
Labels: 1.6.x

#576 Fix/npe service to url
  cluster/src/main/java/com/networknt/cluster/LightCluster.java
Labels: 1.6.x, 2.0.x

#561 Fix/#547 deprecate apis - client module
  client/src/integration/java/com/networknt/client/Http2ClientIT.java
  client/src/main/java/com/networknt/client/AsyncResponse.java
  client/src/main/java/com/networknt/client/AsyncResult.java
  client/src/main/java/com/networknt/client/ClientConfig.java
  client/src/main/java/com/networknt/client/DefaultAsyncResult.java
  client/src/main/java/com/networknt/client/Http2Client.java
  client/src/main/java/com/networknt/client/circuitbreaker/CircuitBreaker.java
  client/src/main/java/com/networknt/client/http/Http2ClientCompletableFutureNoRequest.java
  client/src/main/java/com/networknt/client/http/Http2ClientCompletableFutureWithRequest.java
  client/src/main/java/com/networknt/client/http/Light4jHttp2ClientProvider.java
  client/src/main/java/com/networknt/client/oauth/AuthorizationCodeRequest.java
  client/src/main/java/com/networknt/client/oauth/ClientCredentialsRequest.java
  client/src/main/java/com/networknt/client/oauth/ClientRequestComposerProvider.java
  client/src/main/java/com/networknt/client/oauth/DerefRequest.java
  client/src/main/java/com/networknt/client/oauth/Jwt.java
  client/src/main/java/com/networknt/client/oauth/KeyRequest.java
  client/src/main/java/com/networknt/client/oauth/OauthHelper.java
  client/src/main/java/com/networknt/client/oauth/RefreshTokenRequest.java
  client/src/main/java/com/networknt/client/oauth/SAMLBearerRequest.java
  client/src/main/java/com/networknt/client/oauth/SignKeyRequest.java
  client/src/main/java/com/networknt/client/oauth/SignRequest.java
  client/src/main/java/com/networknt/client/oauth/TokenKeyRequest.java
  client/src/main/java/com/networknt/client/oauth/TokenManager.java
  client/src/main/java/com/networknt/client/oauth/TokenRequest.java
  client/src/main/java/com/networknt/client/oauth/cache/LongestExpireCacheStrategy.java
  security/src/main/java/com/networknt/security/JwtHelper.java
  security/src/main/java/com/networknt/security/JwtIssuer.java
  server/src/integration/java/com/networknt/server/ConsulRegistryIT.java
Labels: 2.0.x

#570 Fix/#523 consul http https connection
  consul/src/main/java/com/networknt/consul/client/ConsulClientImpl.java
  consul/src/main/resources/config/consul.yml
Labels: 1.6.x, 2.0.x

#577 Fix/#573 consul registry notify
  cluster/src/main/java/com/networknt/cluster/LightCluster.java
  consul/src/main/java/com/networknt/consul/ConsulRegistry.java
  consul/src/main/java/com/networknt/consul/ConsulUtils.java
Labels: 1.6.x, 2.0.x, bug

#578 randomly pick up port number for dynamic registry
  server/src/main/java/com/networknt/server/Server.java
Labels: 1.6.x, 2.0.x

#580 fixes #579 when all instances are down and restarted, the client disc…
  cluster/src/main/java/com/networknt/cluster/LightCluster.java
  server/src/main/java/com/networknt/server/Server.java
Labels: 1.6.x, 2.0.x, bug

#582 fixes #578 to use a hashset to track used ports
  server/src/main/java/com/networknt/server/Server.java
Labels: 1.6.x, 2.0.x, bug

#562 Merge to 1.6.x/#547 deprecate apis
  client/src/main/java/com/networknt/client/AsyncResponse.java
  client/src/main/java/com/networknt/client/AsyncResult.java
  client/src/main/java/com/networknt/client/ClientConfig.java
  client/src/main/java/com/networknt/client/DefaultAsyncResult.java
  client/src/main/java/com/networknt/client/Http2Client.java
  client/src/main/java/com/networknt/client/circuitbreaker/CircuitBreaker.java
  client/src/main/java/com/networknt/client/http/Http2ClientCompletableFutureNoRequest.java
  client/src/main/java/com/networknt/client/http/Http2ClientCompletableFutureWithRequest.java
  client/src/main/java/com/networknt/client/http/Light4jHttp2ClientProvider.java
  client/src/main/java/com/networknt/client/oauth/AuthorizationCodeRequest.java
  client/src/main/java/com/networknt/client/oauth/ClientCredentialsRequest.java
  client/src/main/java/com/networknt/client/oauth/ClientRequestComposerProvider.java
  client/src/main/java/com/networknt/client/oauth/DerefRequest.java
  client/src/main/java/com/networknt/client/oauth/Jwt.java
  client/src/main/java/com/networknt/client/oauth/KeyRequest.java
  client/src/main/java/com/networknt/client/oauth/OauthHelper.java
  client/src/main/java/com/networknt/client/oauth/RefreshTokenRequest.java
  client/src/main/java/com/networknt/client/oauth/SAMLBearerRequest.java
  client/src/main/java/com/networknt/client/oauth/SignKeyRequest.java
  client/src/main/java/com/networknt/client/oauth/SignRequest.java
  client/src/main/java/com/networknt/client/oauth/TokenKeyRequest.java
  client/src/main/java/com/networknt/client/oauth/TokenManager.java
  client/src/main/java/com/networknt/client/oauth/TokenRequest.java
  client/src/main/java/com/networknt/client/oauth/cache/LongestExpireCacheStrategy.java
  client/src/main/java/com/networknt/client/ssl/ClientX509ExtendedTrustManager.java
  security/src/main/java/com/networknt/security/JwtHelper.java
Labels: 1.7.x

#587 fixes #586 FormData.FormValue cannot be handled by Jackson JSON parser
  body/src/main/java/com/networknt/body/BodyConverter.java
  body/src/test/java/com/networknt/body/BodyConverterTest.java
  body/src/test/java/com/networknt/body/BodyHandlerTest.java
Labels: 1.6.x, 2.0.x

#589 API-189: Return Json format result from HealthGetHandler
  health/src/main/java/com/networknt/health/HealthConfig.java
  health/src/main/java/com/networknt/health/HealthGetHandler.java
  health/src/main/resources/config/health.yml
  health/src/test/java/com/networknt/health/HealthGetHandlerTest.java
Labels: 1.6.x, 2.0.x
